import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Sidebar } from '@/components/sidebar'
import { ClerkProvider } from '@clerk/nextjs'
import { MapProvider } from '@/components/map-context'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <MapProvider>
            <div className="flex h-screen font-ding">
              <Sidebar />
              <div className="flex-1">{children}</div>
            </div>
          </MapProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
