import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import { zhCN } from '@clerk/localizations'
import { cn } from '@/lib/utils'
import './globals.css'
import { TailwindIndicator } from '@/components/TailwindIndicator'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Position Marker',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider localization={zhCN}>
      <html lang="en">
        <body className={cn(inter.className, 'font-ding')}>
          {children}
          <TailwindIndicator />
        </body>
      </html>
    </ClerkProvider>
  )
}
